In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [77]:
df = pd.read_excel("../data/large_null_dataset.xlsx")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [78]:
df.shape

(5000, 12)

In [79]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department', 'Salary',
       'Experience', 'City', 'Education', 'Performance', 'Projects',
       'Joining_Year'],
      dtype='object')

In [80]:
df.head()

,Employee_ID,Name,Age,Gender,Department,Salary,Experience,City,Education,Performance,Projects,Joining_Year
0,1001.0,NaN,NaN,Female,HR,NaN,NaN,Lucknow,NaN,2.0,NaN,2024.0
1,1002.0,Rohit,59.0,Male,Finance,98179.0,NaN,Delhi,B.Com,3.0,13.0,NaN
2,1003.0,Amit,55.0,Female,Marketing,55069.0,NaN,NaN,MCA,2.0,18.0,2018.0
3,1004.0,Rohit,34.0,Male,Finance,93246.0,NaN,NaN,B.Tech,1.0,NaN,2016.0
4,1005.0,Rohit,47.0,Female,Sales,58560.0,NaN,NaN,NaN,NaN,9.0,2019.0

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   4800 non-null   float64
 1   Name          3580 non-null   object
 2   Age           3316 non-null   float64
 3   Gender        3858 non-null   object
 4   Department    3387 non-null   object
 5   Salary        3118 non-null   float64
 6   Experience    3390 non-null   float64
 7   City          3620 non-null   object
 8   Education     3590 non-null   object
 9   Performance   3370 non-null   float64
 10  Projects      3565 non-null   float64
 11  Joining_Year  3285 non-null   float64
dtypes: float64(7), object(5)
memory usage: 468.9+ KB

In [82]:
df.describe()

,Employee_ID,Age,Salary,Experience,Performance,Projects,Joining_Year
count,4800.000000,3316.000000,3118.000000,3390.000000,3370.000000,3565.000000,3285.000000
mean,3502.647083,39.313631,59583.572803,12.015044,2.976855,9.792987,2020.442009
std,1442.741117,11.338556,23393.714543,7.164266,1.409609,5.468336,3.424148
min,1001.000000,20.000000,20014.000000,0.000000,1.000000,1.000000,2015.000000
25%,2256.750000,30.000000,38414.000000,6.000000,2.000000,5.000000,2017.000000
50%,3500.500000,39.000000,60047.500000,12.000000,3.000000,10.000000,2020.000000
75%,4753.250000,49.000000,80050.500000,18.000000,4.000000,14.000000,2023.000000
max,6000.000000,59.000000,99996.000000,24.000000,5.000000,19.000000,2026.000000

In [83]:
df.isnull().sum()

Employee_ID      200
Name            1420
Age             1684
Gender          1142
Department      1613
Salary          1882
Experience      1610
City            1380
Education       1410
Performance     1630
Projects        1435
Joining_Year    1715
dtype: int64

In [84]:
df.isnull().sum().sum()

np.int64(17121)

In [85]:
df_clean = df.dropna(how="all").copy()

df_clean.shape

(4800, 12)

In [86]:
len(df) - len(df_clean)

200

In [87]:
df_clean.isnull().sum()

Employee_ID        0
Name            1220
Age             1484
Gender           942
Department      1413
Salary          1682
Experience      1410
City            1180
Education       1210
Performance     1430
Projects        1235
Joining_Year    1515
dtype: int64

In [88]:
(df_clean.isnull().mean() * 100).round(2)

Employee_ID      0.00
Name            25.42
Age             30.92
Gender          19.62
Department      29.44
Salary          35.04
Experience      29.38
City            24.58
Education       25.21
Performance     29.79
Projects        25.73
Joining_Year    31.56
dtype: float64

In [89]:
numeric_cols = df_clean.select_dtypes(include="number").columns

categorical_cols = df_clean.select_dtypes(include="object").columns

numeric_cols,categorical_cols

(Index(['Employee_ID', 'Age', 'Salary', 'Experience', 'Performance', 'Projects',
        'Joining_Year'],
       dtype='object'),
 Index(['Name', 'Gender', 'Department', 'City', 'Education'], dtype='object'))

In [90]:
df_clean[numeric_cols].isnull().sum()

Employee_ID        0
Age             1484
Salary          1682
Experience      1410
Performance     1430
Projects        1235
Joining_Year    1515
dtype: int64

In [91]:
df_clean[categorical_cols].isnull().sum()

Name          1220
Gender         942
Department    1413
City          1180
Education     1210
dtype: int64

In [92]:
for col in numeric_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

In [93]:
df_clean[numeric_cols].isnull().sum()

Employee_ID     0
Age             0
Salary          0
Experience      0
Performance     0
Projects        0
Joining_Year    0
dtype: int64

In [94]:
df_clean.isnull().sum().sum()

np.int64(5965)

In [95]:
for col in categorical_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

In [96]:
df_clean[categorical_cols].isnull().sum()

Name          0
Gender        0
Department    0
City          0
Education     0
dtype: int64

In [97]:
df_clean.isnull().sum().sum()

np.int64(0)

In [98]:
df.shape,df_clean.shape

((5000, 12), (4800, 12))

In [99]:
df_clean.dtypes

Employee_ID     float64
Name             object
Age             float64
Gender           object
Department       object
Salary          float64
Experience      float64
City             object
Education        object
Performance     float64
Projects        float64
Joining_Year    float64
dtype: object

In [100]:
integer_cols = [
    "Age",
    "Performance",
    "Projects",
    "Joining_Year"
]

for col in integer_cols:
    df_clean[col] = df_clean[col].astype("Int64")

In [101]:
df_clean.dtypes

Employee_ID     float64
Name             object
Age               Int64
Gender           object
Department       object
Salary          float64
Experience      float64
City             object
Education        object
Performance       Int64
Projects          Int64
Joining_Year      Int64
dtype: object

In [102]:
df_clean["Employee_ID"].isnull().sum()

np.int64(0)

In [103]:
(df_clean["Employee_ID"] % 1 ==0).all()

np.True_

In [104]:
df_clean["Employee_ID"] = df_clean["Employee_ID"].astype("Int64")

In [105]:
df_clean.dtypes

Employee_ID       Int64
Name             object
Age               Int64
Gender           object
Department       object
Salary          float64
Experience      float64
City             object
Education        object
Performance       Int64
Projects          Int64
Joining_Year      Int64
dtype: object

In [106]:
text_cols = [
    "Name",
    "Gender",
    "Department",
    "City",
    "Education"
]

for col in text_cols:
    df_clean[col] = df_clean[col].astype("string")

In [107]:
df_clean.dtypes

Employee_ID              Int64
Name            string[python]
Age                      Int64
Gender          string[python]
Department      string[python]
Salary                 float64
Experience             float64
City            string[python]
Education       string[python]
Performance              Int64
Projects                 Int64
Joining_Year             Int64
dtype: object

In [108]:
df_clean.to_excel("../data/cleaned_dataset.xlsx",index=False)

df_clean.to_csv("../data/cleaned_dataset.csv",index=False)

In [109]:
import os

os.listdir("../data")

['cleaned_data.csv',
 'cleaned_dataset.csv',
 'cleaned_dataset.xlsx',
 'large_null_dataset.xlsx']